### PR TITLE
Token-Filters: partial documentation of filter configuration

### PR DESCRIPTION
**Pull request by pmezard**
Here is a proposal to make the analysis documentation more useful in
practice:
- Explain how analyzers, filters, etc. reference each other
- Explain how custom variants can be created
- Document their configuration entries

Once we agree on the format, I will add similar headers to other
sections and document the ones I know and the trivial ones.

### CODE REVIEW

**Comment by pmezard** [comment]
@mschoch any thoughs on this?

**Comment by mschoch** [comment]
Sorry I had lost track of this one.  I will review it shortly.

**Comment by mschoch** [comment]
The content and formatting looks good to me.  Do you want me to merge this now?  Or do you want to document more of it and have me merge all of it at once?

**Comment by pmezard** [comment]
I would have it merged now, I do not know when I will have time to continue working on this. In the meantime it could work as a template for others.

**Pull request merged**
